linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - errname
    - exhaustive
    - godot
    - goimports
    - lll
    - usestdlibvars
    - whitespace

linters-settings:
  goimports:
    local-prefixes: pkg.nit.so/switchboard