name: go

on:
  push:
    branches:
      - main
  pull_request:
    branches:

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.19

      - uses: actions/checkout@v3

      - name: Get dependencies
        run: |
          go mod download
          go mod verify

      - name: Test
        run: go test -v .

  golangci-lint:
    uses: nint8835/workflows/.github/workflows/golangci-lint.yaml@main
