name: go

on:
  push:
    branches:
      - main
  pull_request:
    branches:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.19

      - uses: actions/checkout@v3

      - name: Get dependencies
        run: |
          go mod download
          go mod verify

      - name: Test
        run: go test -v .

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.19
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          only-new-issues: true
